# Directory to use as root when bundling. dest directories will be
# relative to this directory.
target_directory = "infra/bundle"

# dest: a folder in the bundling target directory
# sources: a list of folders or files to copy into the destination

[[bundles]]
dest = "chat_api"
sources = ["./backend/lambdas/chat_api/"]

[[bundles]]
dest = "step_function_types/python/step_function_types"
sources = ["./backend/layers/step_function_types/"]

[[bundles]]
dest = "websocket_utils/python/websocket_utils"
sources = ["./backend/layers/websocket_utils/"]

[[bundles]]
dest = "connect"
sources = [
    "./backend/lambdas/websocket/connect.py",
    "./backend/lambdas/websocket/websocket_errors.py",
    "./backend/lambdas/websocket/response_utils.py",
    "./backend/lambdas/websocket/validators.py",
    "./backend/lambdas/websocket/__init__.py",
    "./backend/lambdas/websocket/requirements.txt",
]

[[bundles]]
dest = "disconnect"
sources = [
    "./backend/lambdas/websocket/disconnect.py",
    "./backend/lambdas/websocket/websocket_errors.py",
    "./backend/lambdas/websocket/response_utils.py",
    "./backend/lambdas/websocket/validators.py",
    "./backend/lambdas/websocket/__init__.py",
    "./backend/lambdas/websocket/requirements.txt",
]

[[bundles]]
dest = "default"
sources = [
    "./backend/lambdas/websocket/default.py",
    "./backend/lambdas/websocket/websocket_errors.py",
    "./backend/lambdas/websocket/response_utils.py",
    "./backend/lambdas/websocket/validators.py",
    "./backend/lambdas/websocket/__init__.py",
    "./backend/lambdas/websocket/requirements.txt",
]


[[bundles]]
dest = "agentic_retrieval"
sources = ["./backend/lambdas/agentic_retrieval"]