# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class ChatTurn(BaseModel):
    query: typing.Optional[str] = None
    answer: typing.Optional[str] = None

class Document(BaseModel):
    document_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    content: typing.Optional[str] = None
    source: typing.Optional[str] = None
    source_id: typing.Optional[str] = None

class RAGResponse(BaseModel):
    answer: typing.Optional[str] = Field(default=None, description='The conversational answer to the user\'s question, formatted as Markdown')
    relevant_document_ids: typing.List[str] = Field(description='List of document_id values for documents that were directly relevant and used to answer the question')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
